language: python
python:
  - "2.7"

# Use matrix: to explicitly specify the builds
# - Linux: Singular VM with docker, one build for
#          each different image
matrix:
  include:
    - os: linux
      services: docker
      env:
        - DOCKER_IMAGE=rootproject/root-ubuntu16:latest
        - DOCKER_CONTAINER=root-docker
        - SCRIPT_PREFIX_CMD="docker exec $DOCKER_CONTAINER"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      docker pull $DOCKER_IMAGE
      docker run \
             -itd \
             -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
             --name $DOCKER_CONTAINER $DOCKER_IMAGE
    fi

install:
  - pip install -r requirements.txt
# command to run tests
script: pytest